### ISSUE TITLE
Migrate to different hosting

### ISSUE THREAD

**Issue by Philippus** [mefellows/sbt-dotenv#97] opened 2021-04-01 07:16 UTC
On May 1st Bintray will be sunset (https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). @mefellows do you already have plans to move sbt-dotenv somewhere else?

**Comment by mefellows** [comment] 2021-04-06 01:52
Ahhh, good question - I didn't see this announcement!

What's everyone else doing these days? Move back to Central? What would you suggest?

**Comment by Philippus** [comment] 2021-04-08 18:08
I think most are moving to publish on Maven Central.

**Comment by Philippus** [comment] 2021-04-12 14:39
Looks like the brownouts mentioned on that page have already started.

**Comment by renancaju** [comment] 2021-04-12 16:05
Hi, I'm experiencing this issue when trying to build my project that depends on sbt-dotenv. Should I wait for another release? Any estimate on when it will be available again?

**Comment by Philippus** [comment] 2021-04-15 06:31
I think we are covered for existing releases by this: https://github.com/sbt/sbt/issues/6294

**Comment by mefellows** [comment] 2021-04-15 06:44
Thanks @Philippus. 

I'll get this migrated to Maven central this week (now regretting not doing that in the first place :P )

**Comment by mefellows** [comment] 2021-04-27 12:07
@Philippus can you please create yourself a user (or share your current username) at https://issues.sonatype.org/secure/Signup!default.jspa? I've created https://issues.sonatype.org/browse/OSSRH-68099 and will add you as an owner of the org also.

**Comment by mefellows** [comment] 2021-04-27 13:11
From here, I think the process is:

* Add https://github.com/xerial/sbt-sonatype to the project (or another project that can do it, but this seems to be the [official](https://central.sonatype.org/publish/publish-sbt/) [one](https://www.scala-sbt.org/release/docs/Using-Sonatype.html))
* Remove the Bintray plugin
* Update the release step in travis 
* Update the README so everybody knows where to find it.

FYI I've added the `GPG_PASSPHRASE` secret to our repository, so that can be used in builds once we have publish rights.

@Philippus I might need your help, I haven't written any scala since not long after this module 😆

**Comment by Philippus** [comment] 2021-04-27 13:12
My username at sonatype is 'philippus'.

**Comment by mefellows** [comment] 2021-04-27 13:21
Thanks - I've just added you to the ticket now!

**Comment by mefellows** [comment] 2021-04-27 13:21
This actually looks useful too - what do you think https://github.com/olafurpg/sbt-ci-release?

**Comment by Philippus** [comment] 2021-04-27 13:25
Yes, I think that's a good one. A lot of folks are using that.

**Comment by mefellows** [comment] 2021-04-27 13:33
Great. OK, well I think I've created all of the pre-requisite accounts/keys/credentials and have added them to the travis settings. Once I get confirmation that central repo has been setup we can give it a go!

There's a few pieces of our SBT setup that I can't recall how it works/why it's there - would you be OK to give the build setup a go? Otherwise, I can give it a shot and you can tell me what I've done wrong :P 

Also, I so very much appreciate all of your help on this! 🙏

**Comment by mefellows** [comment] 2021-05-01 11:00
Packages are syncing to the OSS release repository (), just waiting for them to setup the sync to Maven Central (see https://issues.sonatype.org/browse/OSSRH-68099?page=com.atlassian.jira.plugin.system.issuetabpanels%3Aall-tabpanel).

Almost there!

**Comment by mefellows** [comment] 2021-05-03 22:46
and we're live: https://repo1.maven.org/maven2/au/com/onegeek/sbt-dotenv_2.12_1.0/2.1.231/

We're not visible in search.maven.org yet, but that sync can take a couple of hours apparently.

Going forward, it should take about 10mins after a release for it to be available to users.

Closing!

**Comment by Philippus** [comment] 2021-05-04 09:50
It's not showing up yet, I'm wondering if we have to switch to Maven-style publishing or something like that. If I compare the directory to https://repo1.maven.org/maven2/com/github/sbt/sbt-release_2.12_1.0/1.0.15/ then I don't see the .pom files.

**Comment by mefellows** [comment] 2021-05-04 09:56
hmm that's a bugger! Is it maybe this we need to configure: https://github.com/xerial/sbt-sonatype#project-rootsonatypesbt ?

**Comment by fernandomora** [comment] 2021-05-23 03:15
I would ask to reopen this issue.
Some automatic dependency update tools like scala-steward and renovate are triggering update to `2.1.231` but build fails because there is no pom file on https://repo1.maven.org/maven2/au/com/onegeek/sbt-dotenv_2.12_1.0/2.1.231/

``` [error] (update) sbt.librarymanagement.ResolveException: Error downloading au.com.onegeek:sbt-dotenv;sbtVersion=1.0;scalaVersion=2.12:2.1.231
[error]   Not found
[error]   Not found
[error]   not found: repo1.maven.org/maven2/au/com/onegeek/sbt-dotenv_2.12_1.0/2.1.231/sbt-dotenv-2.1.231.pom
[error]   not found: /home/runner/.ivy2/local/au.com.onegeek/sbt-dotenv/scala_2.12/sbt_1.0/2.1.231/ivys/ivy.xml
[error]   not found: repo.scala-sbt.org/scalasbt/sbt-plugin-releases/au.com.onegeek/sbt-dotenv/scala_2.12/sbt_1.0/2.1.231/ivys/ivy.xml
[error]   not found: repo.typesafe.com/typesafe/ivy-releases/au.com.onegeek/sbt-dotenv/scala_2.12/sbt_1.0/2.1.231/ivys/ivy.xml```

I'm pretty sure the problem is `publishMavenStyle` is disabled:
https://github.com/mefellows/sbt-dotenv/commit/9360fd24c54fd49a4dc44c90c03d837ac341cc37#diff-5634c415cd8c8504fdb973a3ed092300b43c4b8fc1e184f7249eb29a55511f91L50

**Comment by mefellows** [comment] 2021-05-23 03:42
Just added `publishMavenStyle := true` now. 🤞

**Closed** 2021-05-23 03:42 UTC

**Comment by fernandomora** [comment] 2021-05-23 04:41
I think `publishMavenStyle` is now declared twice the build.sbt, both false and true and probably second one is the actual used 😬 

https://github.com/mefellows/sbt-dotenv/blob/v2.1.232/build.sbt#L9

**Comment by mefellows** [comment] 2021-05-23 04:45
Oh, dear. You're right. I used `git add -p` and forget that I removed it at the bottom. Thanks for picking that up.

**Comment by mefellows** [comment] 2021-05-23 11:29
Looks like that did the trick: https://search.maven.org/artifact/au.com.onegeek/sbt-dotenv/2.1.233/jar. Let me know if that works.

**Comment by fernandomora** [comment] 2021-05-23 12:01
That worked! 👍 
Thanks a lot 😃

**Comment by mefellows** [comment] 2021-05-23 12:52
Great, thanks for helping out!
